### ISSUE TITLE
Picture Doesn't Load

### ISSUE THREAD

**Issue by qw3rtman** [hellyeah/hellyeah.github.io#1]
The image in `index.html` does not load for me. This is most likely due to a Dropbox permission error.

![screen shot 2015-06-04 at 3 59 01 pm](https://cloud.githubusercontent.com/assets/1139621/7994379/a374c914-0ad2-11e5-9af2-0e24e116a3f2.png)

![screen shot 2015-06-04 at 3 58 22 pm](https://cloud.githubusercontent.com/assets/1139621/7994370/8c6aa14e-0ad2-11e5-890f-1b0e8f9fa873.png)

**Comment by hellyeah** [comment]
Switched to imgur <3

**Comment by hellyeah** [comment]
Switched to imgur. Should work meow!

![screen shot 2015-06-04 at 5 51 42 pm](https://cloud.githubusercontent.com/assets/1475361/7997467/6c621cbe-0ae2-11e5-8008-bb7a60613463.png)
